apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mss
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
      matchLabels:
        app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: saikannepalli/frontend1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
