apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mss
  labels:
    app: backend
spec:
  replicas: 3
  selector:
      matchLabels:
        app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: saikannepalli/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
